### ISSUE TITLE
Error in result$content %>% rawToChar : could not find function "%>%"

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/cedarr#1]
Not sure this is a cedarr issue or due to my R just revival from 3.6 to 4 version ;)

```
> querylong<- cedarr::cedarSearch(api.key = "205b1e521f2eaf0ad4a361c438b638a68348bea313caeae310839f919629525d", query="longitude")
Error in result$content %>% rawToChar : could not find function "%>%"
```

**Comment by earnaud** [comment]
Restarting an R session (Ctrl+Shift+F10) might resolve the issue if you still encounter it. I believe it is due to a misdefinition of `%>%` between {cedarr} and other packages loaded in your local environment (like {dplyr} from which it is imported)
